export const MY_LISTINGS_FILTER_KEYS = {
  STATUS: "status",
  MAKE_ID: "make_id",
  MODEL_ID: "model_id",
  SINCE_CREATED_AT: "since_created_at",
  UNTIL_CREATED_AT: "until_created_at",
  ORDER: "order",
  PAGE: "page",
} as const;

export const MY_LISTINGS_FILTER_KEYS_LIST: string[] = [
  MY_LISTINGS_FILTER_KEYS.STATUS,
  MY_LISTINGS_FILTER_KEYS.MAKE_ID,
  MY_LISTINGS_FILTER_KEYS.MODEL_ID,
  MY_LISTINGS_FILTER_KEYS.SINCE_CREATED_AT,
  MY_LISTINGS_FILTER_KEYS.UNTIL_CREATED_AT,
  MY_LISTINGS_FILTER_KEYS.ORDER,
  MY_LISTINGS_FILTER_KEYS.PAGE,
];
