export type DealershipListItem = {
  id: string;
  name: string;
  slug: string;
  avatar_url?: string | null;
  banner_url?: string | null;
  description: string;
  website_url?: string | null;
  email: string;
  phone_code: string;
  phone: string;
  address: string;
  lat?: number;
  lng?: number;
  is_featured: boolean;
  rating: number | null;
  created_at: string;
  updated_at: string;
  members_count: number;
  reviews_count: number;
  vehicles_count?: number;
  distance?: number | null;
};
