import {
  BadgeCheck,
  Barcode,
  Battery,
  Building2,
  Calendar,
  Car,
  CarFront,
  CircleGauge,
  Compass,
  Cog,
  DoorOpen,
  Fuel,
  Gauge,
  IdCard,
  Layers,
  LayoutGrid,
  Leaf,
  Palette,
  PlugZap,
  Route,
  ShieldCheck,
  Tags,
  Zap,
  type LucideIcon,
} from "lucide-react";

const TECHNICAL_SPEC_ICONS: Record<string, LucideIcon> = {
  Marca: Building2,
  Modelo: Car,
  Versión: Layers,
  Año: Calendar,
  Carrocería: LayoutGrid,
  Puertas: DoorOpen,
  Combustible: Fuel,
  "Tipo de vehículo": CarFront,
  Categoría: Tags,
  Condición: BadgeCheck,
  Kilometraje: Gauge,
  Transmisión: Cog,
  Tracción: Compass,
  Potencia: Zap,
  Cilindrada: CircleGauge,
  Color: Palette,
  "Distintivo DGT": Leaf,
  Garantía: ShieldCheck,
  Autonomía: Route,
  "Capacidad batería": Battery,
  "Tiempo de carga": PlugZap,
  Matrícula: IdCard,
  VIN: Barcode,
};

export const getTechnicalSpecIcon = (label: string): LucideIcon =>
  TECHNICAL_SPEC_ICONS[label] ?? Car;
